using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xamarin.Forms;

namespace WaitTime.Views.Home
{
    /// <summary>
    /// Interaction logic for iphone_12_pro_max___1.xaml
	/// Generated by Export Kit - Lightning Storm.
    /// </summary>
    public partial class calendario : ContentPage
    {
        public calendario()
        {
            InitializeComponent();
        }
    }
}
	